import {arabicName,bilingualName,searchConcepts} from './arabic';
import LearningPanel from './learning';
import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [mode,setMode]=useState<'explore'|'learn'|'quiz'>('explore');
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch('/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('تعذر تحميل فهرس التشريح.');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError('تعذر تحميل فهرس التشريح. تحقق من الاتصال ثم أعد المحاولة.');});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return searchConcepts(atlas.concepts,term);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setMode('explore');setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:(details||mode!=='explore')&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> أطلس تشريحي تفاعلي</div><h1>جسم الإنسان<Badge variant="outline" className="edition">ثلاثي الأبعاد</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString('en-US'):'2,234'} جزء تشريحي <span>·</span> BodyParts3D</div></header>
  <nav className="mode-tabs glass" aria-label="وضع الأطلس">{(['explore','learn','quiz'] as const).map((m,i)=><Button key={m} variant="ghost" aria-pressed={mode===m} onClick={()=>{setMode(m);reset();}}>{['استكشف','تعلّم','اختبر نفسك'][i]}</Button>)}</nav>
  {mode!=='explore'&&atlas&&<LearningPanel mode={mode} atlas={atlas} onSelect={c=>{choose(c);setDetails(false);setState(s=>({...s,isolate:true,explode:0}));}} onClose={()=>{setMode('explore');reset();}} onReset={reset}/>}
  <nav className="top-actions" aria-label="لوحات الاستكشاف"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="البحث في التشريح"><Search size={18}/><span>ابحث عن بنية</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="عن الأطلس" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="طبقات التشريح">
   <div className="panel-heading"><span>الأجهزة</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="إغلاق الأجهزة"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>الكل</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>العظام</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>الأعضاء</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`إظهار ${s.name} فقط`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`إظهار ${s.name}`} /></div>)}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString('en-US')} جزء ظاهر</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>إخفاء الكل</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="البحث عن بنية تشريحية"><div className="panel-heading"><span>ابحث عن بنية</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="إغلاق البحث"><X size={18}/></Button></div><Combobox<Concept> modal={false} items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>bilingualName(c.name)} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="القلب، عظم الفخذ، العصب البصري…" aria-label="ابحث بالعربية أو الإنجليزية أو المعرّف" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>لا توجد نتائج مطابقة. جرّب الاسم الإنجليزي لبنية دقيقة.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{arabicName(c.name)??c.name}{arabicName(c.name)&&<small lang="en" dir="ltr">{c.name}</small>}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'جزء':'أجزاء'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'نعرض حتى 80 نتيجة. أضف تفاصيل لتضييق البحث.':'ابحث بالعربية في المصطلحات المتاحة، أو بالإنجليزية في جميع البنى.'}</p></section>}
  <nav className="view-controls glass" aria-label="التحكم بالكاميرا">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={['منظور مائل','أمامي','جانبي','خلفي'][i]} aria-label={['منظور مائل','أمامي','جانبي','خلفي'][i]}><span>{['¾','أ','ج','خ'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'إيقاف الدوران':'تدوير الجسم'} title="دوران تلقائي" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="إعادة ضبط العرض والطبقات" title="إعادة الضبط" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?bilingualName(chosen.name):'البنية المحددة'):state.explode>.95?'جميع البنى التشريحية':state.explode>.05?'بنى متباعدة':'جسم إنسان بالغ · ذكر'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="فتح طبقات الأجهزة"><Layers3 size={20}/><span>الأجهزة</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">تفكيك التشريح</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>متصل</span><span>كل الأجزاء</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="تجميع وإعادة ضبط"><RotateCcw size={18}/><span>إعادة الضبط</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'اسحب للتحريك':'اسحب للتدوير'} <b>·</b> باعد إصبعيك للتكبير <b>·</b> انقر للاستكشاف</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>المصدر والحقوق <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>جارٍ تجهيز التشريح</strong><span>{progress}% · تحميل {atlas?.parts.length.toLocaleString('en-US')??'2,234'} جزء</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>إعادة تحميل العارض</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'التشريح'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen&&(arabicName(chosen.name)??chosen.name)}</SheetTitle>{chosen&&arabicName(chosen.name)&&<div className="english-term" lang="en" dir="ltr">{chosen.name}</div>}{chosen&&!arabicName(chosen.name)&&<small>المصطلح العربي غير متاح بعد</small>}</div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">نبذة عن الجهاز الذي تنتمي إليه هذه البنية</span>}<div className="structure-meta"><span>معرّف الأطلس<strong>{chosen?.id}</strong></span><span>الأجزاء المحددة<strong>{state.selected.length.toLocaleString('en-US')}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>البنى المتضمنة</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{bilingualName(p.name)}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>و{selectedParts.length-50} جزءًا إضافيًا.</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">عرض المصدر التشريحي <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'إظهار التشريح المحيط':'عزل البنية'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>إلغاء التحديد</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">المصدر والنطاق</div><SheetTitle className="structure-title">جسم الإنسان</SheetTitle><SheetDescription>استكشف نموذجًا تشريحيًا مرجعيًا لذكر بالغ من BodyParts3D.</SheetDescription><div className="about-copy"><p><strong>ذكر بالغ · BodyParts3D</strong><br/>2,234 شبكة هندسية و3,432 مفهومًا تشريحيًا مسمى من نموذج مرجعي لذكر بالغ.</p><p>لا يشمل هذا المرجع جميع البنى البشرية أو الاختلافات التشريحية. قد يضم المفهوم عدة أجزاء؛ وتُعرض كل شبكة مرة واحدة.</p><p>الألوان وتجميع الأجهزة مخصصة للاستكشاف. بُسّطت الهندسة للويب، وتقدم الأوصاف سياقًا تعليميًا عامًا. هذا مرجع تشريحي وليس أداة للتشخيص أو الجراحة.</p><h3>المصدر</h3><p>النسخة العربية: جسم الإنسان، مبنية على human-atlas. الشيفرة بترخيص MIT؛ لم تُغيّر هندسة التشريح أو معرّفاتها. تغطية المصطلحات العربية جزئية وقابلة للتوسعة.</p><a href="https://github.com/ashemag/human-atlas" target="_blank" rel="noreferrer">المستودع الأصلي · MIT</a><p>BodyParts3D، © مركز قواعد بيانات علوم الحياة (The Database Center for Life Science)، مرخّص بموجب رخصة المشاع الإبداعي: نَسب المُصنَّف 4.0 دولي (CC BY 4.0).</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">ترخيص البيانات <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">الهندسة والبيانات الأصلية <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">قراءة المنشور الأصلي <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
